import "./globals.css";
import LayoutProvider from "@/components/LayoutProvider";
import ReduxStoreProvider from "@/components/ReduxStoreProvider";
import "@/stylesheets/customClasses.css";

export const metadata = {
  title: "Car rental app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxStoreProvider>
      <LayoutProvider>{children}</LayoutProvider>
    </ReduxStoreProvider>
  );
}
