import './globals.css';
import LayoutProvider from '@/components/LayoutProvider';

export const metadata = {
  title: 'Car rental app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
  
    
    <LayoutProvider>{children}</LayoutProvider>
   

  );
}
